"""Shared Teger AI contracts."""
from .analysis import (  # noqa: F401
    AiExplanation,
    AiExplanationStatus,
    AiKeyPoint,
    AiUsage,
    AnalysisRequest,
    AnalysisSummary,
    ContentType,
    DetectorReport,
    DetectorStatus,
    Evidence,
    IntelligenceCoverage,
    NormalizedUrl,
    ProviderMode,
    RecommendedAction,
    Severity,
    ThreatVerdict,
    Verdict,
)
